# Generated by Django 2.0.2 on 2018-02-25 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animal', '0006_auto_20180225_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('female', 'Hembra'), ('male', 'Macho'), ('indeterminate', 'Desconocido')], default='indeterminate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='state',
            field=models.ManyToManyField(to='complaint.State'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='type',
            field=models.ManyToManyField(to='animal.Type'),
        ),
    ]
