# Generated by Django 2.0.2 on 2018-02-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='injured',
            field=models.CharField(choices=[('YES', 'sí'), ('NO', 'no')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='complaint',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
