# Generated by Django 2.0.2 on 2018-02-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('female', 'Hembra'), ('male', 'Macho'), ('indeterminate', 'Desconocido')], default='indeterminate', max_length=20)),
                ('estimated_age', models.IntegerField(default=0)),
            ],
        ),
    ]
