# Generated by Django 2.0.2 on 2018-02-25 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_animal_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_adoption',
            field=models.BooleanField(default=False),
        ),
    ]
