# Generated by Django 2.0.2 on 2018-02-25 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20180225_0256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='types',
            new_name='type',
        ),
    ]
