# Generated by Django 2.0.2 on 2018-02-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naturalperson',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='naturalperson',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
